[package]
name = "my-business"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sample-rust-service-core= { path = "../sample-rust-service-core" }
zmq = "0.9"