[package]
name = "service-installer"
version = "0.1.0"
edition = "2018"

[dependencies]
windows-service="0.4.0"
clap="2.33.3"
colored = "2.0.0"

[dependencies.winapi]
version = "0.3.9"
default-features = true
features = ["debugapi"]