[package]
name = "sample-rust-service"
version = "0.1.0"
edition = "2018"

[dependencies]
windows-service="0.4.0"
widestring = "0.4.3"

[dependencies.winapi]
version = "0.3.9"
default-features = true
features = ["debugapi"]
